spring:
  autoconfiguration:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration # Turn off security auto configuration
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    password: iamdaghuy
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never #Run the schema.sql file
      continue-on-error: false #Stop the application if errors found